// packages/dusk-cli/templates/typescript-react/src/App.tsx
import { PlayerId } from "dusk-games-sdk/multiplayer"
import { useEffect, useState } from "react"

import selectSoundAudio from "./assets/select.wav"
import { GameState } from "./logic.ts"

const selectSound = new Audio(selectSoundAudio)

function App() {
  const [game, setGame] = useState<GameState>()
  const [yourPlayerId, setYourPlayerId] = useState<PlayerId | undefined>()

  useEffect(() => {
    Dusk.initClient({
      onChange: ({ game, action, yourPlayerId }) => {
        setGame(game)
        setYourPlayerId(yourPlayerId)

        if (action && action.name === "claimCell") selectSound.play()
      },
    })
  }, [])

  if (!game) {
    return <div>Loading...</div>
  }

  const { winCombo, cells, lastMovePlayerId, playerIds, freeCells } = game

  return (
    <>
      <div id="board" className={!lastMovePlayerId ? "initial" : ""}>
        {cells.map((cell, cellIndex) => {
          const cellValue = cells[cellIndex]

          return (
            <button
              key={cellIndex}
              onClick={() => Dusk.actions.claimCell(cellIndex)}
              data-player={(cellValue !== null
                ? playerIds.indexOf(cellValue)
                : -1
              ).toString()}
              data-dim={String(
                (winCombo && !winCombo.includes(cellIndex)) ||
                  (!freeCells && !winCombo)
              )}
              {...(cells[cellIndex] ||
              lastMovePlayerId === yourPlayerId ||
              winCombo
                ? { "data-disabled": "" }
                : {})}
            />
          )
        })}
      </div>
      <ul id="playersSection">
        {playerIds.map((playerId, index) => {
          const player = Dusk.getPlayerInfo(playerId)

          return (
            <li
              key={playerId}
              data-player={index.toString()}
              data-your-turn={String(
                playerIds[index] !== lastMovePlayerId && !winCombo && freeCells
              )}
            >
              <img src={player.avatarUrl} />
              <span>
                {player.displayName}
                {player.playerId === yourPlayerId && (
                  <span>
                    <br />
                    (You)
                  </span>
                )}
              </span>
            </li>
          )
        })}
      </ul>
    </>
  )
}

export default App

// packages/dusk-cli/templates/typescript-vue/src/App.vue
<script setup lang="ts">
import { Player, PlayerId } from "dusk-games-sdk/multiplayer"
import { ref, onMounted } from "vue"

import selectSoundAudio from "./assets/select.wav"
import CellButton from "./components/CellButton.vue"
import PlayerContainer from "./components/PlayerContainer.vue"
import { Cells } from "./logic.ts"

const selectSound = new Audio(selectSoundAudio)

const gCells = ref<Cells>([])
const gPlayers = ref<Player[]>([])
const gYourPlayerId = ref<PlayerId | undefined>()
const gLastMovePlayerId = ref<PlayerId | null>(null)
const gWinCombo = ref<number[] | null>(null)
const gFreeCells = ref<boolean>(false)

function getPlayerIndex(playerId: PlayerId | null): number {
  if (playerId === null) {
    return -1
  }
  const players = gPlayers.value
  for (let i = 0; i < players.length; ++i) {
    if (players[i].playerId === playerId) {
      return i
    }
  }
  return -1
}

onMounted(() => {
  Dusk.initClient({
    onChange: ({ game, yourPlayerId, action, event }) => {
      const isInitialization =
        gCells.value.length === 0 || event?.name === "stateSync"

      gCells.value = game.cells
      gYourPlayerId.value = yourPlayerId
      gLastMovePlayerId.value = game.lastMovePlayerId
      gWinCombo.value = game.winCombo
      gFreeCells.value = !!game.freeCells

      if (isInitialization) {
        gPlayers.value = game.playerIds.map((playerId) =>
          Dusk.getPlayerInfo(playerId)
        )
      }

      if (action && action.name === "claimCell") selectSound.play()
    },
  })
})
</script>

<template>
  <div id="board" :class="{ initial: !gLastMovePlayerId }">
    <CellButton
      v-for="(cell, index) in gCells"
      :key="index"
      :cell-index="index"
      :player-index="getPlayerIndex(cell)"
      :dim="
        (gWinCombo && !gWinCombo.includes(index)) || (!gFreeCells && !gWinCombo)
      "
      :disabled="cell || gLastMovePlayerId === gYourPlayerId || gWinCombo"
    />
  </div>
  <ul id="playersSection">
    <PlayerContainer
      v-for="(player, index) in gPlayers"
      :key="player.playerId"
      :player-index="index"
      :avatar-url="player.avatarUrl"
      :display-name="player.displayName"
      :tag="player.playerId === gYourPlayerId ? '(You)' : ''"
      :is-turn-holder="
        player.playerId !== gLastMovePlayerId && !gWinCombo && gFreeCells
      "
    />
  </ul>
</template>
